import type { Metadata } from "next";
import { getPlanDisplayName } from "@/lib/plan-labels";

export const SITE_URL = "https://nextreport.in";
export const SITE_NAME = "NextReport";
export const SUPPORT_EMAIL = "hello@nextreport.in";
export const TWITTER_HANDLE = "@nextreportin";

/** Default social share image — generated by src/app/opengraph-image.tsx (1200×630). */
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "NextReport — Meta, Google Ads, TikTok & GA4 reporting for agencies",
} as const;

/** High-intent and long-tail terms — used on homepage and key landing pages. */
export const DEFAULT_KEYWORDS = [
  "meta ads reporting tool",
  "google ads reporting tool",
  "tiktok ads reporting tool",
  "ga4 reporting tool",
  "google analytics 4 reporting",
  "automated ad reporting software",
  "agency reporting software",
  "client reporting automation",
  "meta ads report generator",
  "meta ads powerpoint report",
  "csv to powerpoint",
  "csv to pptx",
  "csv to pdf",
  "meta marketing api reporting",
  "google ads api sync",
  "tiktok marketing api",
  "digital marketing reports India",
  "performance marketing report",
  "weekly ad performance report",
  "meta ads csv export",
] as const;

export type SitemapEntry = {
  path: string;
  changeFrequency: "always" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | "never";
  priority: number;
};

/** Public marketing routes included in sitemap.xml — no auth-only or noindex pages. */
export const PUBLIC_SITEMAP_ROUTES: SitemapEntry[] = [
  { path: "/", changeFrequency: "weekly", priority: 1 },
  { path: "/how-it-works", changeFrequency: "monthly", priority: 0.9 },
  { path: "/help/download", changeFrequency: "monthly", priority: 0.85 },
  { path: "/pricing", changeFrequency: "weekly", priority: 0.9 },
  { path: "/about", changeFrequency: "monthly", priority: 0.6 },
  { path: "/contact", changeFrequency: "monthly", priority: 0.6 },
  { path: "/refer", changeFrequency: "monthly", priority: 0.5 },
  { path: "/privacy", changeFrequency: "yearly", priority: 0.3 },
  { path: "/terms", changeFrequency: "yearly", priority: 0.3 },
  { path: "/data-deletion", changeFrequency: "yearly", priority: 0.3 },
];

type PageMetadataInput = {
  title: string;
  description: string;
  path: string;
  keywords?: string[];
  noIndex?: boolean;
};

function ogImages() {
  return [{ ...OG_IMAGE }];
}

/** Consistent Open Graph, Twitter, canonical, and hreflang metadata for public pages. */
export function pageMetadata({
  title,
  description,
  path,
  keywords = [...DEFAULT_KEYWORDS],
  noIndex = false,
}: PageMetadataInput): Metadata {
  const url = `${SITE_URL}${path}`;

  return {
    title,
    description,
    keywords,
    authors: [{ name: SITE_NAME, url: SITE_URL }],
    creator: SITE_NAME,
    publisher: SITE_NAME,
    alternates: {
      canonical: url,
      languages: {
        "en-IN": url,
        en: url,
        "x-default": url,
      },
    },
    openGraph: {
      type: "website",
      url,
      siteName: SITE_NAME,
      title: `${title} — ${SITE_NAME}`,
      description,
      locale: "en_IN",
      images: ogImages(),
    },
    twitter: {
      card: "summary_large_image",
      site: TWITTER_HANDLE,
      creator: TWITTER_HANDLE,
      title: `${title} — ${SITE_NAME}`,
      description,
      images: [OG_IMAGE.url],
    },
    robots: noIndex
      ? { index: false, follow: false }
      : {
          index: true,
          follow: true,
          googleBot: {
            index: true,
            follow: true,
            "max-image-preview": "large",
            "max-snippet": -1,
          },
        },
  };
}

/** Root layout defaults — individual pages override via pageMetadata(). */
export const ROOT_METADATA: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Automated Ad & Website Reports in 2 Minutes",
    template: `%s — ${SITE_NAME}`,
  },
  description:
    "Send polished Meta, Google Ads, TikTok & GA4 client reports in under 2 minutes. API sync or CSV — branded .pptx, live link & PDF. Free 7-day trial.",
  keywords: [...DEFAULT_KEYWORDS],
  authors: [{ name: SITE_NAME, url: SITE_URL }],
  creator: SITE_NAME,
  publisher: SITE_NAME,
  applicationName: SITE_NAME,
  category: "Business",
  alternates: {
    canonical: SITE_URL,
    languages: {
      "en-IN": SITE_URL,
      en: SITE_URL,
      "x-default": SITE_URL,
    },
  },
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: SITE_NAME,
    locale: "en_IN",
    title: `Automated Ad & Website Reports in 2 Minutes — ${SITE_NAME}`,
    description:
      "Send polished Meta, Google Ads, TikTok & GA4 client reports in under 2 minutes. API sync or CSV — branded .pptx, live link & PDF.",
    images: ogImages(),
  },
  twitter: {
    card: "summary_large_image",
    site: TWITTER_HANDLE,
    creator: TWITTER_HANDLE,
    images: [OG_IMAGE.url],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: [
      { url: "/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon.ico", sizes: "any" },
    ],
    shortcut: "/favicon-32.png",
    apple: "/favicon-large.png",
  },
  other: {
    "theme-color": "#0d1b2e",
  },
};

export function rootMetadataWithVerification(): Metadata {
  const google = process.env.GOOGLE_SITE_VERIFICATION?.trim();
  const bing = process.env.BING_SITE_VERIFICATION?.trim();
  if (!google && !bing) return ROOT_METADATA;

  return {
    ...ROOT_METADATA,
    verification: {
      ...(google ? { google } : {}),
      ...(bing ? { other: { "msvalidate.01": bing } } : {}),
    },
  };
}

export const HOME_JSON_LD = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": `${SITE_URL}/#organization`,
      name: SITE_NAME,
      url: SITE_URL,
      logo: `${SITE_URL}/logo.png`,
      email: SUPPORT_EMAIL,
      description:
        "Automated Meta Ads, Google Ads, TikTok Ads, and GA4 reporting for digital agencies — branded PowerPoint, live share links, and PDF exports in under two minutes.",
      contactPoint: {
        "@type": "ContactPoint",
        email: SUPPORT_EMAIL,
        contactType: "customer support",
        availableLanguage: ["English", "Hindi"],
      },
      address: {
        "@type": "PostalAddress",
        addressCountry: "IN",
      },
    },
    {
      "@type": "WebSite",
      "@id": `${SITE_URL}/#website`,
      url: SITE_URL,
      name: SITE_NAME,
      publisher: { "@id": `${SITE_URL}/#organization` },
      inLanguage: "en",
    },
    {
      "@type": "SoftwareApplication",
      "@id": `${SITE_URL}/#software`,
      name: SITE_NAME,
      applicationCategory: "BusinessApplication",
      operatingSystem: "Web",
      url: SITE_URL,
      offers: [
        {
          "@type": "Offer",
          price: "699",
          priceCurrency: "INR",
          description: `${getPlanDisplayName("starter")} plan from ₹699/month with 7-day free trial`,
        },
        {
          "@type": "Offer",
          price: "8",
          priceCurrency: "USD",
          description: `${getPlanDisplayName("starter")} plan from $8/month with 7-day free trial`,
        },
      ],
      description:
        "Connect Meta Ads, Google Ads, TikTok Ads, or GA4 via API — or upload a CSV — to generate client-ready PowerPoint (.pptx) reports, live browser share links, and PDF downloads with AI-written insights.",
      featureList: [
        "Meta Marketing API sync",
        "Google Ads API sync",
        "TikTok Marketing API sync",
        "Google Analytics 4 website reporting",
        "CSV to PowerPoint (.pptx)",
        "CSV to PDF",
        "Live browser share link",
        "AI campaign summaries",
      ],
    },
  ],
} as const;

export interface FaqSchemaItem {
  question: string;
  answer: string;
}

export function faqPageJsonLd(items: FaqSchemaItem[]) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: items.map((item) => ({
      "@type": "Question",
      name: item.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: item.answer,
      },
    })),
  };
}

export interface HowToStepSchema {
  name: string;
  text: string;
}

export function howToJsonLd(name: string, description: string, steps: HowToStepSchema[]) {
  return {
    "@context": "https://schema.org",
    "@type": "HowTo",
    name,
    description,
    totalTime: "PT2M",
    step: steps.map((step) => ({
      "@type": "HowToStep",
      name: step.name,
      text: step.text,
    })),
  };
}

export function breadcrumbJsonLd(items: { name: string; path: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.name,
      item: `${SITE_URL}${item.path}`,
    })),
  };
}

/** Shared FAQ copy for How It Works + Pricing schema markup. */
export const PRODUCT_FAQ_SCHEMA: FaqSchemaItem[] = [
  {
    question: "Which ad platforms does NextReport support?",
    answer:
      "NextReport supports Meta Ads, Google Ads, TikTok Ads, and Google Analytics 4 (GA4) website reporting. Connect via official API or upload a CSV export from each platform.",
  },
  {
    question: "What file formats can I upload?",
    answer:
      "NextReport accepts CSV, Excel (XLSX, XLS), TSV, and TXT files exported from Meta Ads Manager, Google Ads, TikTok Ads, or GA4.",
  },
  {
    question: "How long does it take to generate a report?",
    answer:
      "Most reports generate in under 2 minutes from API sync or CSV upload through to a downloadable PowerPoint (.pptx), live browser link, or PDF.",
  },
  {
    question: "Is there a free trial?",
    answer:
      "Yes. NextReport offers a 7-day free trial with full access. No credit card is required to start.",
  },
  {
    question: "Can I use NextReport for multiple clients?",
    answer:
      "Yes. NextReport is built for agencies — create a separate client workspace for each account. The Agency plan supports up to 10 clients; Professional includes unlimited clients.",
  },
];

export const HOW_IT_WORKS_STEPS_SCHEMA: HowToStepSchema[] = [
  {
    name: "Connect or upload",
    text: "Connect Meta, Google Ads, TikTok, or GA4 via official API in Account settings, or upload a CSV export in the report wizard.",
  },
  {
    name: "Select campaigns and dates",
    text: "Choose which campaigns and ad sets to include and pick your reporting period.",
  },
  {
    name: "Confirm objectives",
    text: "Review auto-detected campaign objectives — leads, purchases, traffic, reach, and more — and correct any that look wrong.",
  },
  {
    name: "Review metrics",
    text: "Preview the metric cards on each campaign slide and add or remove metrics as needed.",
  },
  {
    name: "Generate and share",
    text: "Click Generate to download a branded PowerPoint (.pptx), share a live browser link, or export a PDF.",
  },
];
