// Homepage copy/structure overhaul — replaces the old testimonials section
// (fake quotes/names removed entirely) with a real, checkable proof point:
// a downloadable sample of the actual PPTX output. See public/sample-
// report.pptx's own note in the repo for how that file gets placed.
export function SampleReportSection() {
  return (
    <section className="bg-navy-panel px-6 py-20">
      <div className="mx-auto max-w-3xl">
        <div className="mx-auto w-full max-w-[80%] rounded-xl border-l-4 border-accent-orange bg-navy p-10 text-center">
          <h2 className="text-2xl font-semibold text-white sm:text-3xl">See it before you sign up</h2>
          <p className="mt-4 text-base leading-relaxed text-ink-muted">
            Download a real report generated by NextReport — same format, same AI insights, same
            professional output your clients will receive.
          </p>
          <a
            href="/sample-report.pptx"
            className="mt-8 inline-block rounded-md bg-accent-orange px-6 py-3 text-sm font-semibold text-navy hover:bg-accent-orange-hover"
          >
            Download Sample Report →
          </a>
          <p className="mt-4 text-xs text-ink-muted">No signup required. Opens in PowerPoint or Google Slides.</p>
        </div>
      </div>
    </section>
  );
}
