import { buildCombinedTotalTableGrid } from "@/lib/nre/report-data";
import { buildGoogleCombinedTotalTableGrid } from "@/lib/nre/google-report-data";
import type { ShareReportData, ShareCampaignData, ShareAdSetData, ShareChartData } from "@/lib/nre/share-report";
import { applyShareVisibility } from "@/lib/nre/share-report";
import { resolveChartFooterInsight } from "@/lib/nre/share-chart-projection";
import { ShareChartDonut } from "@/components/share-chart-donut";
import type { DeliveryStatusIndicator } from "@/lib/nre/delivery-status";
import type { DynamicMetricValue } from "@/lib/nre/dynamic-metrics";
import { resolveMetricIconId, type MetricIconId } from "@/lib/pptx/metric-icons";

/**
 * The public share page's full presentational tree (app/r/[token]/page.tsx)
 * — a faithful, all-CSS HTML replica of every slide in the generated PPTX
 * (Round J), built from Report.summaryJson alone (lib/nre/share-report.ts)
 * with no further data fetching. Pulled into its own module so it can be
 * rendered from a fixture — no DB, no Next.js request context — for the
 * empirical visual check this session's "run tsc/eslint/vitest/build, then
 * look at the real thing" pattern otherwise couldn't reach for a page whose
 * only real caller needs a live Postgres connection.
 */

export function reportTypeLabel(data: ShareReportData): string {
  return data.reportType === "MONTHLY" ? "Monthly Performance Report" : "Weekly Performance Report";
}

/** Reuses the same category resolution the PPT metric cards use (metric-icons.ts) — its 7 categories map 1:1 onto public/metric-icons/*.png, except "cost" (a per-unit currency metric like COST PER LEAD), which has no cost.png and instead shares the cost-per-result.png art. */
const ICON_FILE_BY_CATEGORY: Record<MetricIconId, string> = {
  spend: "spend",
  reach: "reach",
  impressions: "impressions",
  results: "results",
  ctr: "ctr",
  cpc: "cpc",
  cost: "cost-per-result",
};

function metricIconFile(metric: DynamicMetricValue): string {
  return ICON_FILE_BY_CATEGORY[resolveMetricIconId(metric)];
}

/** Share-page-only Metric Guide copy — more specific than the PPT legend's own dictionary explanations (lib/nre/meta-dictionary.ts / google-dictionary.ts), which stay untouched since they're shared with the actual deck. Keyed by the same uppercase term the guide already displays (ShareReportData["metricGuide"][number]["term"]). */
const METRIC_EXPLANATIONS: Record<string, string> = {
  "QUOTE REQUEST SUBMITTED": "Number of quote requests submitted through your ads",
  "WEBSITE LEADS": "Number of leads submitted through your website landing page",
  "META FORM LEADS": "Number of leads submitted through Meta instant forms",
  PURCHASES: "Number of purchases completed through your ads",
  "INITIATE CHECKOUT": "Number of times people began the checkout process",
  "ADD TO CART": "Number of times people added items to their cart",
  "LINK CLICKS": "Number of clicks on links within your ads",
  "LANDING PAGE VIEWS": "Number of times people landed on your website after clicking",
  THRUPLAYS: "Number of times your video was watched to completion or 15 seconds",
  "VIDEO VIEWS": "Number of times your video was watched",
  REACH: "Number of unique people who saw your ad at least once",
  IMPRESSIONS: "Total number of times your ads were displayed",
  "CTR (ALL)": "Percentage of people who clicked after seeing your ad",
  "CPC (ALL)": "Average cost for each click on your ad",
  CPM: "Average cost per 1,000 impressions",
  FREQUENCY: "Average number of times each person saw your ad",
  "MESSAGING CONVERSATIONS": "Number of conversations started through your ads",
  "APP INSTALLS": "Number of times your app was installed through your ads",
  ROAS: "Return on ad spend — revenue generated for every dollar spent on ads",
};

/**
 * Fix 6 — the generic fallback for any metric term not given its own
 * specific copy above. "Cost per X" terms get "Average cost to achieve
 * each X through your ads" (never "Cost per X generated by your campaign",
 * which reads oddly for a cost metric — nothing is "generated"); every
 * other term gets "X delivered through your ads".
 */
function getExplanation(label: string): string {
  const known = METRIC_EXPLANATIONS[label];
  if (known) return known;
  const titleCased = label.charAt(0) + label.slice(1).toLowerCase();
  if (label.startsWith("COST PER ")) {
    return `Average cost to achieve each ${label.slice("COST PER ".length).toLowerCase()} through your ads`;
  }
  return `${titleCased} delivered through your ads`;
}

function StatusBadge({ status }: { status: DeliveryStatusIndicator }) {
  if (!status) return null;
  return (
    <span className="shrink-0 rounded-full border border-accent-orange/40 bg-accent-orange/15 px-2.5 py-0.5 text-[14px] font-semibold uppercase tracking-wide text-accent-orange">
      {status}
    </span>
  );
}

function MetricGrid({ metrics, assetBaseUrl = "" }: { metrics: DynamicMetricValue[]; assetBaseUrl?: string }) {
  if (metrics.length === 0) return null;
  const iconPrefix = assetBaseUrl.replace(/\/$/, "");
  return (
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
      {metrics.map((m, i) => (
        <div key={`${m.key}-${i}`} className="rounded-lg border border-navy-border bg-navy-panel px-3 py-4 text-center">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={`${iconPrefix}/metric-icons/${metricIconFile(m)}.png`}
            alt=""
            width={20}
            height={20}
            className="mx-auto mb-2 opacity-90"
          />
          <p className="truncate text-[14px] font-semibold uppercase tracking-wide text-accent-orange" style={{ letterSpacing: "0.5px" }}>
            {m.label}
          </p>
          <p className="mt-1 truncate text-[22px] font-bold text-ink sm:text-[28px]">{m.value}</p>
        </div>
      ))}
    </div>
  );
}

function DateAndFrequency({ dateRange, adFrequency }: { dateRange: string; adFrequency: string }) {
  return (
    <div className="mt-1 text-[16px] text-ink-muted">
      {dateRange}
      {adFrequency && ` · ${adFrequency}`}
    </div>
  );
}

/** Fix 6 (round K) — secondary, muted, uppercase report-type line above the campaign/ad-set name, matching the PPT's own now-secondary "YOUR WEEKLY/MONTHLY PERFORMANCE REPORT" heading. */
function CardReportTypeLabel({ label }: { label: string }) {
  return (
    <div
      className="text-[14px] font-semibold text-ink-muted"
      style={{ letterSpacing: "1px", textTransform: "uppercase", marginBottom: "6px" }}
    >
      {label}
    </div>
  );
}

function AiCopyBlock({ heading, text }: { heading: string; text: string }) {
  if (!text) return null;
  return (
    <div className="mt-4">
      <h4 className="text-[14px] font-bold uppercase tracking-wide text-accent-orange">{heading}</h4>
      <p className="mt-1.5 text-[17px] leading-[1.6] text-ink">{text}</p>
    </div>
  );
}

function SlideCard({ children }: { children: React.ReactNode }) {
  return (
    <div className="overflow-hidden rounded-lg border border-navy-border bg-navy p-4 shadow-[0_4px_20px_rgba(0,0,0,0.25)] sm:p-6 md:p-8">
      {children}
    </div>
  );
}

/**
 * Fix 6 (round K) — heading hierarchy: the campaign name is now the most
 * prominent text on the card (matching the PPT's own campaign/ad-set slide
 * hierarchy), with the report type ("Weekly/Monthly Performance Report")
 * demoted to a small muted line above it, and the "(Campaign)" type label
 * riding the same line as the name in its own smaller amber run.
 */
function CampaignCard({
  campaign,
  reportType,
  assetBaseUrl = "",
}: {
  campaign: ShareCampaignData;
  reportType: string;
  assetBaseUrl?: string;
}) {
  return (
    <SlideCard>
      <div className="flex flex-wrap items-start justify-between gap-2">
        <div className="min-w-0 flex-1 overflow-hidden">
          <CardReportTypeLabel label={reportType} />
          <h3 className="box-border max-w-full break-words text-[22px] font-bold leading-snug text-ink [overflow-wrap:anywhere] sm:text-[28px]">
            {campaign.campaignName}
            <span className="text-accent-orange" style={{ fontSize: "14px", fontWeight: 400 }}>
              {" "}
              (Campaign)
            </span>
          </h3>
        </div>
        <StatusBadge status={campaign.statusIndicator} />
      </div>
      <DateAndFrequency dateRange={campaign.dateRange} adFrequency={campaign.adFrequency} />

      <div className="mt-5">
        <MetricGrid metrics={campaign.metrics} assetBaseUrl={assetBaseUrl} />
      </div>

      <AiCopyBlock heading="Campaign Summary" text={campaign.aiSummary} />
      <AiCopyBlock heading="Key Insights & Updates" text={campaign.aiInsights} />
    </SlideCard>
  );
}

/** Ad-set slides lead with the AD SET name (not the campaign name) as the prominent heading, matching the PPT's own heading logic — the campaign name becomes secondary context underneath. Falls back to the bare campaign name (no colored type label, no secondary line) when there's no real ad-set name to label as one, same fallback the PPT uses. */
function AdSetCard({
  adSet,
  platform,
  reportType,
  assetBaseUrl = "",
}: {
  adSet: ShareAdSetData;
  platform: ShareReportData["platform"];
  reportType: string;
  assetBaseUrl?: string;
}) {
  const adSetLabel = platform === "GOOGLE" ? " (Ad Group)" : " (Ad Set)";
  const hasAdSetName = adSet.adSetName.length > 0;
  const primaryName = hasAdSetName ? adSet.adSetName : adSet.campaignName;
  return (
    <SlideCard>
      <div className="flex flex-wrap items-start justify-between gap-2">
        <div className="min-w-0 flex-1 overflow-hidden">
          <CardReportTypeLabel label={reportType} />
          <h3 className="box-border max-w-full break-words text-[22px] font-bold leading-snug text-ink [overflow-wrap:anywhere] sm:text-[28px]">
            {primaryName}
            {hasAdSetName && (
              <span style={{ color: "#63b3ed", fontSize: "14px", fontWeight: 400 }}>{adSetLabel}</span>
            )}
          </h3>
          {hasAdSetName && (
            <p className="mt-0.5 break-words text-[17px] text-ink-muted [overflow-wrap:anywhere]">{adSet.campaignName}</p>
          )}
        </div>
        <StatusBadge status={adSet.statusIndicator} />
      </div>
      <DateAndFrequency dateRange={adSet.dateRange} adFrequency={adSet.adFrequency} />

      <div className="mt-5">
        <MetricGrid metrics={adSet.metrics} assetBaseUrl={assetBaseUrl} />
      </div>

      <AiCopyBlock heading="Campaign Summary" text={adSet.aiSummary} />
      <AiCopyBlock heading="Key Insights & Updates" text={adSet.aiInsights} />
    </SlideCard>
  );
}

function VisualResultBar({
  name,
  color,
  statLine,
  barPct,
}: {
  name: string;
  color: string;
  statLine: string;
  barPct: number;
}) {
  const widthPct = Math.max(0, Math.min(100, barPct));
  return (
    <div className="min-w-0">
      <p className="truncate text-[14px] font-bold leading-tight text-ink">{name}</p>
      <p className="mt-1 overflow-hidden text-ellipsis whitespace-nowrap text-[14px] font-bold text-ink">{statLine}</p>
      <div className="mt-1 h-7 overflow-hidden rounded bg-[#1e293b]">
        <div className="h-full rounded" style={{ width: `${widthPct}%`, backgroundColor: `#${color}` }} />
      </div>
    </div>
  );
}

/** Browser chart slide — two-panel budget + results layout (matches editable PPT slide). */
export function ShareMtdOverviewSlide({ chart }: { chart: ShareChartData }) {
  const model = chart.visualSlide;
  if (!model) return null;

  return (
    <SlideCard>
      <h2 className="line-clamp-2 text-center text-[22px] font-bold leading-tight text-[#94a3b8] sm:text-[28px]">{model.title}</h2>

      <div className="mt-4 grid grid-cols-1 gap-3 min-[720px]:grid-cols-[348px_1fr]">
        <div className="rounded-lg border border-navy-border p-4" style={{ backgroundColor: "#111f35" }}>
          <p className="text-[16px] font-bold uppercase tracking-wide text-[#94a3b8]">{model.leftHeading}</p>
          {model.groupedDonut && model.groupedDonut.length > 0 ? (
            <div className="mt-4 space-y-3">
              <div className="relative mx-auto h-[204px] w-[204px]">
                <ShareChartDonut
                  segments={model.groupedDonut.map((s) => ({
                    name: s.name,
                    spendLabel: s.spendLabel,
                    percentage: s.percentage,
                    color: s.color,
                  }))}
                  totalSpendLabel={model.groupedDonutCenterLabel}
                  size={204}
                />
              </div>
              {model.groupedDonut.map((seg) => (
                <p key={seg.name} className="overflow-hidden text-ellipsis whitespace-nowrap text-[14px] text-ink">
                  <span className="mr-2 inline-block h-2.5 w-2.5 shrink-0 rounded-sm align-middle" style={{ backgroundColor: `#${seg.color}` }} />
                  {seg.name} · {seg.spendLabel} · {seg.percentage}%
                </p>
              ))}
            </div>
          ) : null}
        </div>

        <div className="rounded-lg border border-navy-border p-4" style={{ backgroundColor: "#111f35" }}>
          <p className="text-[16px] font-bold uppercase tracking-wide text-[#94a3b8]">{model.rightHeading}</p>
          <div className="mt-4 space-y-4">
            {model.resultBars.map((bar) => (
              <VisualResultBar key={bar.name} {...bar} />
            ))}
          </div>
        </div>
      </div>

      <p className="mt-5 text-center text-[16px] text-[#94a3b8]">{model.summaryLine}</p>
    </SlideCard>
  );
}

/**
 * Reproduces the exact PPT Combined Total slide's row-hiding rules
 * (pptx/fill-tags.ts's buildTableSlideXml) so this table only ever shows
 * the same rows the client would see in the deck: the Period row is
 * dropped for a Monthly report or when there's no Previous Month Data, and
 * the MTD row is additionally dropped when it would duplicate the Period
 * row's own month.
 */
function CombinedTotalTable({ data, compact = false }: { data: ShareReportData; compact?: boolean }) {
  const grid =
    data.platform === "GOOGLE"
      ? buildGoogleCombinedTotalTableGrid(data.mtdRow, data.tableHeaderLabels)
      : buildCombinedTotalTableGrid(data.periodRow, data.mtdRow, data.tableHeaderLabels);

  const hidePeriodRow = data.reportType === "MONTHLY" || !data.periodRow.hasData;
  const hideMtdRow = !hidePeriodRow && data.periodRow.sameMonthAsCurrentMTD;
  const [headerRow, mtdRow, periodRow] = grid;

  const bodyRows: { cells: string[]; isPeriod: boolean }[] = [
    ...(hideMtdRow ? [] : [{ cells: mtdRow, isPeriod: false }]),
    ...(hidePeriodRow ? [] : [{ cells: periodRow, isPeriod: true }]),
  ];

  if (bodyRows.length === 0) return null;

  return (
    <div className={compact ? "print-combined-table overflow-x-auto rounded-lg border border-navy-border" : "overflow-x-auto rounded-lg border border-navy-border"}>
      <table
        className={
          compact
            ? "w-full border-collapse text-left text-[12px]"
            : "w-full min-w-[640px] border-collapse text-left text-[16px]"
        }
      >
        <thead>
          <tr className="bg-navy-border">
            {headerRow.map((h, i) => (
              <th
                key={i}
                className={
                  compact
                    ? "px-1.5 py-2 text-[11px] font-semibold uppercase tracking-wide text-ink"
                    : "whitespace-nowrap px-4 py-3 text-[14px] font-semibold uppercase tracking-wide text-ink"
                }
              >
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {bodyRows.map((row, ri) => (
            <tr key={ri} className={row.isPeriod ? "bg-navy-panel" : "bg-navy"}>
              {row.cells.map((cell, ci) => (
                <td
                  key={ci}
                  className={
                    (compact
                      ? "px-1.5 py-2 text-[12px] text-ink "
                      : "whitespace-nowrap px-4 py-3 text-[16px] text-ink ") +
                    (ci === 0 ? "text-left font-semibold" : "text-center")
                  }
                >
                  {cell}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function MetricGuideSection({ metricGuide }: { metricGuide: ShareReportData["metricGuide"] }) {
  if (metricGuide.length === 0) return null;
  return (
    <SlideCard>
      <h2 className="text-[22px] font-bold text-ink sm:text-[28px]">Metric Abbreviation Guide</h2>
      <div className="mt-5 grid grid-cols-1 gap-x-8 gap-y-4 sm:grid-cols-2">
        {metricGuide.map((entry, i) => (
          <div key={`${entry.term}-${i}`} className="min-w-0 overflow-hidden">
            <p className="line-clamp-2 break-words text-[15px] font-bold uppercase tracking-wide text-accent-orange">
              {entry.term}
            </p>
            <p className="mt-1 line-clamp-4 break-words text-[15px] leading-[1.5] text-ink-muted">
              {getExplanation(entry.term)}
            </p>
          </div>
        ))}
      </div>
    </SlideCard>
  );
}

export function ShareReportView({
  data,
  shareToken,
  mode = "share",
  assetBaseUrl = "",
}: {
  data: ShareReportData;
  shareToken?: string;
  mode?: "share" | "print";
  /** Prefix for /metric-icons in PDF export (e.g. https://nextreport.in). */
  assetBaseUrl?: string;
}) {
  const isPrint = mode === "print";
  const slideClass = isPrint ? "print-slide mb-0" : "mb-6";
  const coverSlideClass = isPrint ? "print-slide print-cover-slide mb-0" : slideClass;
  const visibleData = applyShareVisibility(data);
  const generatedDate = new Date(visibleData.generatedAt).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const adSets = visibleData.adSets ?? [];
  const chart = visibleData.chart ?? null;
  const metricGuide = visibleData.metricGuide ?? [];
  const showCombinedTotal = visibleData.visibility?.combinedTotal !== false;
  const showMetricGuide = visibleData.visibility?.metricGuide !== false;
  const showOverview = visibleData.visibility?.overview !== false;
  const showCover = visibleData.visibility?.cover !== false;

  return (
    <div
      id={isPrint ? "share-report-print" : "share-report-page"}
      className={isPrint ? "bg-navy" : "min-h-screen"}
      style={
        isPrint
          ? {
              fontFamily: "var(--font-inter), sans-serif",
              backgroundColor: "#0d1b2e",
              backgroundImage: "radial-gradient(circle, #1e3a5f 1px, transparent 1px)",
              backgroundSize: "32px 32px",
            }
          : {
              fontFamily: "var(--font-inter), sans-serif",
              backgroundColor: "#0d1b2e",
              backgroundImage: "radial-gradient(circle, #1e3a5f 1px, transparent 1px)",
              backgroundSize: "32px 32px",
            }
      }
    >
      {!isPrint ? (
      <header
        className="sticky top-0 z-10 border-b border-navy-border px-3 py-2 sm:px-6 sm:py-0"
        style={{ backgroundColor: "#0d1b2e" }}
      >
        <div className="mx-auto flex max-w-[960px] items-center justify-between gap-2 sm:min-h-[56px] sm:gap-3">
          <div className="flex min-w-0 items-center gap-1.5 sm:gap-2">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src="/logo.png"
              alt="NextReport logo"
              className="h-7 w-7 shrink-0 sm:h-9 sm:w-9"
            />
            <span className="truncate text-[17px] font-bold text-ink sm:text-[22px]" style={{ fontFamily: "var(--font-inter), sans-serif" }}>
              NextReport
            </span>
          </div>
          <div className="flex shrink-0 items-center gap-1.5 sm:gap-2">
            <span className="hidden text-[15px] text-white md:inline">Powered by NextReport</span>
            {shareToken ? (
              <a
                href={`/api/r/${shareToken}/download`}
                className="inline-flex items-center justify-center rounded-md border border-accent-orange px-2.5 py-1.5 text-[12px] font-semibold leading-none text-white hover:bg-accent-orange/10 sm:px-3.5 sm:py-2 sm:text-[14px]"
                style={{ backgroundColor: "#1e293b" }}
              >
                <span className="hidden min-[400px]:inline">Download </span>PPTX
              </a>
            ) : null}
            {shareToken && visibleData.publishedAt ? (
              <a
                href={`/api/r/${shareToken}/download-pdf`}
                className="inline-flex items-center justify-center rounded-md border border-[#63b3ed] px-2.5 py-1.5 text-[12px] font-semibold leading-none text-white hover:bg-[#63b3ed]/10 sm:px-3.5 sm:py-2 sm:text-[14px]"
                style={{ backgroundColor: "#1e293b" }}
              >
                <span className="hidden min-[400px]:inline">Download </span>PDF
              </a>
            ) : null}
          </div>
        </div>
      </header>
      ) : null}

      <main className={isPrint ? "mx-auto max-w-[960px] px-6 py-4" : "mx-auto max-w-[960px] px-3 py-4 sm:px-6 sm:py-6"}>
        {/* Cover slide replica */}
        {showCover ? (
        <section className={coverSlideClass}>
          <div
            className={`mx-auto w-full max-w-2xl overflow-hidden rounded-lg border border-navy-border bg-navy-panel px-4 py-6 shadow-[0_4px_20px_rgba(0,0,0,0.25)] sm:px-8 sm:py-9 md:px-10 md:py-10 ${isPrint ? "" : "sm:aspect-video"}`}
          >
            <div className="flex min-h-0 flex-col items-center justify-center px-1 text-center sm:h-full">
              <div
                className="inline-flex max-w-full items-center gap-2 rounded-full"
                style={{ backgroundColor: "#1e293b", border: "1px solid #334155", padding: "3px 10px" }}
              >
                <span
                  className="h-1.5 w-1.5 shrink-0 rounded-full sm:h-2 sm:w-2"
                  style={{ backgroundColor: visibleData.platform === "GOOGLE" ? "#4285F4" : "#1877F2" }}
                />
                <span className="text-[11px] font-semibold uppercase text-[#94a3b8] sm:text-[13px]" style={{ letterSpacing: "0.08em" }}>
                  {visibleData.platform === "GOOGLE" ? "GOOGLE ADS" : "META ADS"}
                </span>
              </div>
              <h1
                className={`mt-3 max-w-full break-words font-bold leading-tight text-ink [overflow-wrap:anywhere] ${
                  isPrint ? "text-[28px]" : "text-[22px] sm:text-[30px] md:text-[34px]"
                }`}
              >
                {visibleData.accountName}
              </h1>
              <p className="mt-1.5 text-[13px] tracking-wide text-ink-muted sm:mt-2 sm:text-[16px]">
                {reportTypeLabel(visibleData).toUpperCase()}
              </p>
              <p className="mt-1 text-[13px] text-ink-muted sm:mt-1.5 sm:text-[16px]">{visibleData.cover.dateRange}</p>
              <div className="my-3 h-px w-16 bg-navy-border sm:my-4 sm:w-24" />
              <p className="max-w-full break-words px-1 text-[13px] font-medium leading-snug text-ink sm:text-[16px]">
                {visibleData.cover.healthBadge}
              </p>
            </div>
          </div>
          {visibleData.isPaused && visibleData.pausedMessage && (
            <p className="mx-auto mt-4 max-w-2xl rounded-md border border-navy-border bg-navy-panel px-4 py-3 text-center text-[16px] text-ink-muted">
              {visibleData.pausedMessage}
            </p>
          )}
        </section>
        ) : null}

        {visibleData.campaigns.map((c) => (
          <section key={`campaign-${c.campaignName}`} className={slideClass}>
            <CampaignCard campaign={c} reportType={reportTypeLabel(visibleData)} assetBaseUrl={assetBaseUrl} />
          </section>
        ))}

        {adSets.map((a, i) => (
          <section key={`adset-${a.campaignName}-${a.adSetName}-${i}`} className={slideClass}>
            <AdSetCard adSet={a} platform={visibleData.platform} reportType={reportTypeLabel(visibleData)} assetBaseUrl={assetBaseUrl} />
          </section>
        ))}

        {showOverview && chart && chart.donutSegments && (
          <section className={slideClass}>
            <ShareMtdOverviewSlide chart={chart} />
          </section>
        )}

        {showCombinedTotal && (
        <section className={slideClass}>
          <SlideCard>
            <h2 className="mb-4 text-[22px] font-bold text-ink sm:text-[28px]">Monthly Campaign Performance Overview</h2>
            <CombinedTotalTable data={visibleData} compact={isPrint} />
          </SlideCard>
        </section>
        )}

        {showMetricGuide && (
        <section className={slideClass}>
          <MetricGuideSection metricGuide={metricGuide} />
        </section>
        )}
      </main>

      {!isPrint && (
      <footer style={{ textAlign: "center", padding: "32px 24px", borderTop: "1px solid #1e3a5f", marginTop: "40px" }}>
        <div style={{ color: "#94a3b8", fontSize: "13px" }}>This report was generated using NextReport · nextreport.in</div>
        <div style={{ color: "#64748b", fontSize: "12px", marginTop: "4px" }}>Generated on {generatedDate}</div>
      </footer>
      )}
    </div>
  );
}
