import { buildCombinedTotalTableGrid } from "@/lib/nre/report-data";
import { buildGoogleCombinedTotalTableGrid } from "@/lib/nre/google-report-data";
import type { ShareReportData, ShareCampaignData, ShareAdSetData, ShareChartData } from "@/lib/nre/share-report";
import { applyShareVisibility } from "@/lib/nre/share-report";
import { formatDonutSegmentStats, resolveChartFooterInsight } from "@/lib/nre/share-chart-projection";
import { ShareChartDonut } from "@/components/share-chart-donut";
import type { DeliveryStatusIndicator } from "@/lib/nre/delivery-status";
import type { DynamicMetricValue } from "@/lib/nre/dynamic-metrics";
import { resolveMetricIconId, type MetricIconId } from "@/lib/pptx/metric-icons";

/**
 * The public share page's full presentational tree (app/r/[token]/page.tsx)
 * — a faithful, all-CSS HTML replica of every slide in the generated PPTX
 * (Round J), built from Report.summaryJson alone (lib/nre/share-report.ts)
 * with no further data fetching. Pulled into its own module so it can be
 * rendered from a fixture — no DB, no Next.js request context — for the
 * empirical visual check this session's "run tsc/eslint/vitest/build, then
 * look at the real thing" pattern otherwise couldn't reach for a page whose
 * only real caller needs a live Postgres connection.
 */

export function reportTypeLabel(data: ShareReportData): string {
  return data.reportType === "MONTHLY" ? "Monthly Performance Report" : "Weekly Performance Report";
}

/** Reuses the same category resolution the PPT metric cards use (metric-icons.ts) — its 7 categories map 1:1 onto public/metric-icons/*.png, except "cost" (a per-unit currency metric like COST PER LEAD), which has no cost.png and instead shares the cost-per-result.png art. */
const ICON_FILE_BY_CATEGORY: Record<MetricIconId, string> = {
  spend: "spend",
  reach: "reach",
  impressions: "impressions",
  results: "results",
  ctr: "ctr",
  cpc: "cpc",
  cost: "cost-per-result",
};

function metricIconFile(metric: DynamicMetricValue): string {
  return ICON_FILE_BY_CATEGORY[resolveMetricIconId(metric)];
}

/** Share-page-only Metric Guide copy — more specific than the PPT legend's own dictionary explanations (lib/nre/meta-dictionary.ts / google-dictionary.ts), which stay untouched since they're shared with the actual deck. Keyed by the same uppercase term the guide already displays (ShareReportData["metricGuide"][number]["term"]). */
const METRIC_EXPLANATIONS: Record<string, string> = {
  "QUOTE REQUEST SUBMITTED": "Number of quote requests submitted through your ads",
  "WEBSITE LEADS": "Number of leads submitted through your website landing page",
  "META FORM LEADS": "Number of leads submitted through Meta instant forms",
  PURCHASES: "Number of purchases completed through your ads",
  "INITIATE CHECKOUT": "Number of times people began the checkout process",
  "ADD TO CART": "Number of times people added items to their cart",
  "LINK CLICKS": "Number of clicks on links within your ads",
  "LANDING PAGE VIEWS": "Number of times people landed on your website after clicking",
  THRUPLAYS: "Number of times your video was watched to completion or 15 seconds",
  "VIDEO VIEWS": "Number of times your video was watched",
  REACH: "Number of unique people who saw your ad at least once",
  IMPRESSIONS: "Total number of times your ads were displayed",
  "CTR (ALL)": "Percentage of people who clicked after seeing your ad",
  "CPC (ALL)": "Average cost for each click on your ad",
  CPM: "Average cost per 1,000 impressions",
  FREQUENCY: "Average number of times each person saw your ad",
  "MESSAGING CONVERSATIONS": "Number of conversations started through your ads",
  "APP INSTALLS": "Number of times your app was installed through your ads",
  ROAS: "Return on ad spend — revenue generated for every dollar spent on ads",
};

/**
 * Fix 6 — the generic fallback for any metric term not given its own
 * specific copy above. "Cost per X" terms get "Average cost to achieve
 * each X through your ads" (never "Cost per X generated by your campaign",
 * which reads oddly for a cost metric — nothing is "generated"); every
 * other term gets "X delivered through your ads".
 */
function getExplanation(label: string): string {
  const known = METRIC_EXPLANATIONS[label];
  if (known) return known;
  const titleCased = label.charAt(0) + label.slice(1).toLowerCase();
  if (label.startsWith("COST PER ")) {
    return `Average cost to achieve each ${label.slice("COST PER ".length).toLowerCase()} through your ads`;
  }
  return `${titleCased} delivered through your ads`;
}

function StatusBadge({ status }: { status: DeliveryStatusIndicator }) {
  if (!status) return null;
  return (
    <span className="shrink-0 rounded-full border border-accent-orange/40 bg-accent-orange/15 px-2.5 py-0.5 text-[11px] font-semibold uppercase tracking-wide text-accent-orange">
      {status}
    </span>
  );
}

function MetricGrid({ metrics }: { metrics: DynamicMetricValue[] }) {
  if (metrics.length === 0) return null;
  return (
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
      {metrics.map((m, i) => (
        <div key={`${m.key}-${i}`} className="rounded-lg border border-navy-border bg-navy-panel px-3 py-4 text-center">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={`/metric-icons/${metricIconFile(m)}.png`}
            alt=""
            width={20}
            height={20}
            className="mx-auto mb-2 opacity-90"
          />
          <p className="truncate text-[10px] font-semibold uppercase tracking-wide text-accent-orange" style={{ letterSpacing: "0.5px" }}>
            {m.label}
          </p>
          <p className="mt-1 truncate text-[22px] font-bold text-ink">{m.value}</p>
        </div>
      ))}
    </div>
  );
}

function DateAndFrequency({ dateRange, adFrequency }: { dateRange: string; adFrequency: string }) {
  return (
    <div className="mt-1 text-[12px] text-ink-muted">
      {dateRange}
      {adFrequency && ` · ${adFrequency}`}
    </div>
  );
}

/** Fix 6 (round K) — secondary, muted, uppercase report-type line above the campaign/ad-set name, matching the PPT's own now-secondary "YOUR WEEKLY/MONTHLY PERFORMANCE REPORT" heading. */
function CardReportTypeLabel({ label }: { label: string }) {
  return (
    <div
      className="text-[11px] font-semibold text-ink-muted"
      style={{ letterSpacing: "1px", textTransform: "uppercase", marginBottom: "6px" }}
    >
      {label}
    </div>
  );
}

function AiCopyBlock({ heading, text }: { heading: string; text: string }) {
  if (!text) return null;
  return (
    <div className="mt-4">
      <h4 className="text-[11px] font-bold uppercase tracking-wide text-accent-orange">{heading}</h4>
      <p className="mt-1.5 text-[14px] leading-[1.6] text-ink">{text}</p>
    </div>
  );
}

function SlideCard({ children }: { children: React.ReactNode }) {
  return (
    <div className="rounded-lg border border-navy-border bg-navy p-6 shadow-[0_4px_20px_rgba(0,0,0,0.25)] sm:p-8">
      {children}
    </div>
  );
}

/**
 * Fix 6 (round K) — heading hierarchy: the campaign name is now the most
 * prominent text on the card (matching the PPT's own campaign/ad-set slide
 * hierarchy), with the report type ("Weekly/Monthly Performance Report")
 * demoted to a small muted line above it, and the "(Campaign)" type label
 * riding the same line as the name in its own smaller amber run.
 */
function CampaignCard({ campaign, reportType }: { campaign: ShareCampaignData; reportType: string }) {
  return (
    <SlideCard>
      <div className="flex flex-wrap items-start justify-between gap-2">
        <div>
          <CardReportTypeLabel label={reportType} />
          <h3 className="line-clamp-2 text-[20px] font-bold text-ink">
            {campaign.campaignName}
            <span className="text-accent-orange" style={{ fontSize: "14px", fontWeight: 400 }}>
              {" "}
              (Campaign)
            </span>
          </h3>
        </div>
        <StatusBadge status={campaign.statusIndicator} />
      </div>
      <DateAndFrequency dateRange={campaign.dateRange} adFrequency={campaign.adFrequency} />

      <div className="mt-5">
        <MetricGrid metrics={campaign.metrics} />
      </div>

      <AiCopyBlock heading="Campaign Summary" text={campaign.aiSummary} />
      <AiCopyBlock heading="Key Insights & Updates" text={campaign.aiInsights} />
    </SlideCard>
  );
}

/** Ad-set slides lead with the AD SET name (not the campaign name) as the prominent heading, matching the PPT's own heading logic — the campaign name becomes secondary context underneath. Falls back to the bare campaign name (no colored type label, no secondary line) when there's no real ad-set name to label as one, same fallback the PPT uses. */
function AdSetCard({ adSet, platform, reportType }: { adSet: ShareAdSetData; platform: ShareReportData["platform"]; reportType: string }) {
  const adSetLabel = platform === "GOOGLE" ? " (Ad Group)" : " (Ad Set)";
  const hasAdSetName = adSet.adSetName.length > 0;
  const primaryName = hasAdSetName ? adSet.adSetName : adSet.campaignName;
  return (
    <SlideCard>
      <div className="flex flex-wrap items-start justify-between gap-2">
        <div>
          <CardReportTypeLabel label={reportType} />
          <h3 className="line-clamp-2 text-[20px] font-bold text-ink">
            {primaryName}
            {hasAdSetName && (
              <span style={{ color: "#63b3ed", fontSize: "14px", fontWeight: 400 }}>{adSetLabel}</span>
            )}
          </h3>
          {hasAdSetName && <p className="mt-0.5 text-[13px] text-ink-muted">{adSet.campaignName}</p>}
        </div>
        <StatusBadge status={adSet.statusIndicator} />
      </div>
      <DateAndFrequency dateRange={adSet.dateRange} adFrequency={adSet.adFrequency} />

      <div className="mt-5">
        <MetricGrid metrics={adSet.metrics} />
      </div>

      <AiCopyBlock heading="Campaign Summary" text={adSet.aiSummary} />
      <AiCopyBlock heading="Key Insights & Updates" text={adSet.aiInsights} />
    </SlideCard>
  );
}

function MtdOverviewSlide({ chart }: { chart: ShareChartData }) {
  const kpiTiles = [
    { value: chart.snapshot.mtdSpendLabel, label: "Ad spend this month" },
    { value: chart.snapshot.primaryResultsValue, label: chart.snapshot.primaryResultsLabel },
    { value: chart.snapshot.primaryCprValue, label: chart.snapshot.primaryCprLabel },
    { value: chart.snapshot.budgetPctUsed || "—", label: chart.snapshot.budgetPctUsed ? "Budget used" : "Budget" },
  ];

  return (
    <SlideCard>
      <h2 className="text-center text-[24px] font-bold text-[#94a3b8]">{chart.title}</h2>
      <p className="mt-1 text-center text-[16px] font-medium text-[#e2e8f0]">{chart.subtitle}</p>

      <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">
        {kpiTiles.map((tile) => (
          <div
            key={tile.label}
            className="rounded-lg border border-navy-border px-3 py-4 text-center"
            style={{ backgroundColor: "#131d30" }}
          >
            <p className="text-[22px] font-bold text-ink">{tile.value}</p>
            <p className="mt-1 text-[10px] font-semibold uppercase tracking-wide text-accent-orange">{tile.label}</p>
          </div>
        ))}
      </div>

      {chart.donutSegments.length > 0 ? (
        <div className="mt-6 grid grid-cols-1 items-center gap-6 min-[720px]:grid-cols-[220px_1fr]">
          <div className="relative mx-auto shrink-0">
            <ShareChartDonut segments={chart.donutSegments} totalSpendLabel={chart.totalSpendLabel} size={220} />
          </div>
          <ul className="space-y-2.5">
            {chart.donutSegments.map((seg) => (
              <li key={seg.name} className="flex items-start gap-2.5 text-[15px] text-ink">
                <span className="mt-1 h-3.5 w-3.5 shrink-0 rounded-sm" style={{ backgroundColor: `#${seg.color}` }} />
                <span className="min-w-0 break-words">
                  <span className="block font-semibold">{seg.name}</span>
                  <span className="mt-0.5 block text-[14px] text-[#94a3b8]">
                    {formatDonutSegmentStats(seg.percentage, seg.spendLabel)}
                  </span>
                </span>
              </li>
            ))}
          </ul>
        </div>
      ) : (
        <p className="mt-6 text-center text-[14px] text-[#e2e8f0]">No spend recorded this month yet.</p>
      )}

      <p className="mt-5 text-center text-[14px] font-medium text-[#e2e8f0]">
        {resolveChartFooterInsight(chart)}
      </p>
    </SlideCard>
  );
}

/**
 * Reproduces the exact PPT Combined Total slide's row-hiding rules
 * (pptx/fill-tags.ts's buildTableSlideXml) so this table only ever shows
 * the same rows the client would see in the deck: the Period row is
 * dropped for a Monthly report or when there's no Previous Month Data, and
 * the MTD row is additionally dropped when it would duplicate the Period
 * row's own month.
 */
function CombinedTotalTable({ data }: { data: ShareReportData }) {
  const grid =
    data.platform === "GOOGLE"
      ? buildGoogleCombinedTotalTableGrid(data.mtdRow, data.tableHeaderLabels)
      : buildCombinedTotalTableGrid(data.periodRow, data.mtdRow, data.tableHeaderLabels);

  const hidePeriodRow = data.reportType === "MONTHLY" || !data.periodRow.hasData;
  const hideMtdRow = !hidePeriodRow && data.periodRow.sameMonthAsCurrentMTD;
  const [headerRow, periodRow, mtdRow] = grid;

  const bodyRows: { cells: string[]; isPeriod: boolean }[] = [
    ...(hidePeriodRow ? [] : [{ cells: periodRow, isPeriod: true }]),
    ...(hideMtdRow ? [] : [{ cells: mtdRow, isPeriod: false }]),
  ];

  if (bodyRows.length === 0) return null;

  return (
    <div className="space-y-2">
      {data.combinedTotalStory ? (
        <p className="text-center text-[16px] leading-snug text-ink" style={{ marginBottom: "12px" }}>
          {data.combinedTotalStory}
        </p>
      ) : null}
    <div className="overflow-x-auto rounded-lg border border-navy-border">
      <table className="w-full min-w-[640px] border-collapse text-left text-[13px]">
        <thead>
          <tr className="bg-navy-border">
            {headerRow.map((h, i) => (
              <th key={i} className="whitespace-nowrap px-4 py-3 text-[11px] font-semibold uppercase tracking-wide text-ink">
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {bodyRows.map((row, ri) => (
            <tr key={ri} className={row.isPeriod ? "bg-navy-panel" : "bg-navy"}>
              {row.cells.map((cell, ci) => (
                <td
                  key={ci}
                  className={
                    "whitespace-nowrap px-4 py-3 text-[13px] text-ink " +
                    (ci === 0 ? "text-left font-semibold" : "text-center")
                  }
                >
                  {cell}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
    </div>
  );
}

function MetricGuideSection({ metricGuide }: { metricGuide: ShareReportData["metricGuide"] }) {
  if (metricGuide.length === 0) return null;
  return (
    <SlideCard>
      <h2 className="text-[22px] font-bold text-ink">Metric Abbreviation Guide</h2>
      <div className="mt-5 grid grid-cols-1 gap-x-8 gap-y-4 sm:grid-cols-2">
        {metricGuide.map((entry, i) => (
          <div key={`${entry.term}-${i}`}>
            <p className="text-[12px] font-bold uppercase tracking-wide text-accent-orange">{entry.term}</p>
            <p className="mt-1 text-[11px] leading-[1.5] text-ink-muted">{getExplanation(entry.term)}</p>
          </div>
        ))}
      </div>
    </SlideCard>
  );
}

export function ShareReportView({
  data,
  shareToken,
  mode = "share",
}: {
  data: ShareReportData;
  shareToken?: string;
  mode?: "share" | "print";
}) {
  const isPrint = mode === "print";
  const slideClass = isPrint ? "print-slide mb-0" : "mb-6";
  const visibleData = applyShareVisibility(data);
  const generatedDate = new Date(visibleData.generatedAt).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const adSets = visibleData.adSets ?? [];
  const chart = visibleData.chart ?? null;
  const metricGuide = visibleData.metricGuide ?? [];
  const showCombinedTotal = visibleData.visibility?.combinedTotal !== false;
  const showMetricGuide = visibleData.visibility?.metricGuide !== false;
  const showOverview = visibleData.visibility?.overview !== false;

  return (
    <div
      id={isPrint ? "share-report-print" : "share-report-page"}
      className={isPrint ? "bg-navy" : "min-h-screen"}
      style={
        isPrint
          ? { fontFamily: "var(--font-inter), sans-serif", backgroundColor: "#0d1b2e" }
          : {
              fontFamily: "var(--font-inter), sans-serif",
              backgroundColor: "#0d1b2e",
              backgroundImage: "radial-gradient(circle, #1e3a5f 1px, transparent 1px)",
              backgroundSize: "32px 32px",
            }
      }
    >
      {!isPrint ? (
      <header
        className="sticky top-0 z-10 border-b border-navy-border px-4 sm:px-6"
        style={{ backgroundColor: "#0d1b2e", minHeight: "60px" }}
      >
        <div className="mx-auto flex max-w-[960px] items-center justify-between gap-3" style={{ minHeight: "60px" }}>
          <div className="flex items-center gap-2">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src="/logo.png" alt="NextReport logo" style={{ height: "40px", width: "40px", display: "block" }} />
            <span className="text-[20px] font-bold text-ink" style={{ fontFamily: "var(--font-inter), sans-serif" }}>
              NextReport
            </span>
          </div>
          <div className="flex items-center gap-3">
            <span className="hidden text-[14px] text-white sm:inline">Powered by NextReport</span>
            {shareToken ? (
              <a
                href={`/api/r/${shareToken}/download`}
                className="flex items-center rounded-md border border-accent-orange px-4 text-[13px] font-semibold text-white hover:bg-accent-orange/10"
                style={{ backgroundColor: "#1e293b", height: "44px" }}
              >
                Download PPTX
              </a>
            ) : null}
            {shareToken && visibleData.publishedAt ? (
              <a
                href={`/api/r/${shareToken}/download-pdf`}
                className="flex items-center rounded-md border border-[#63b3ed] px-4 text-[13px] font-semibold text-white hover:bg-[#63b3ed]/10"
                style={{ backgroundColor: "#1e293b", height: "44px" }}
              >
                Download PDF
              </a>
            ) : null}
          </div>
        </div>
      </header>
      ) : null}

      <main className={isPrint ? "mx-auto max-w-[960px] px-6 py-4" : "mx-auto max-w-[960px] px-4 py-6 sm:px-6"}>
        {/* Cover slide replica */}
        <section className={slideClass}>
          <div className="mx-auto aspect-video w-full max-w-2xl rounded-lg border border-navy-border bg-navy-panel px-6 py-8 shadow-[0_4px_20px_rgba(0,0,0,0.25)] sm:px-10 sm:py-10">
            <div className="flex h-full flex-col items-center justify-center text-center">
              <div
                className="inline-flex items-center gap-2 rounded-full"
                style={{ backgroundColor: "#1e293b", border: "1px solid #334155", padding: "4px 12px" }}
              >
                <span
                  className="h-2 w-2 shrink-0 rounded-full"
                  style={{ backgroundColor: visibleData.platform === "GOOGLE" ? "#4285F4" : "#1877F2" }}
                />
                <span className="text-[11px] font-semibold uppercase" style={{ color: "#94a3b8", letterSpacing: "2px" }}>
                  {visibleData.platform === "GOOGLE" ? "GOOGLE ADS" : "META ADS"}
                </span>
              </div>
              <h1 className="mt-4 line-clamp-2 text-[32px] font-bold text-ink">{visibleData.accountName}</h1>
              <p className="mt-2 text-[16px] tracking-wide text-ink-muted">{reportTypeLabel(visibleData).toUpperCase()}</p>
              <p className="mt-2 text-[14px] text-ink-muted">{visibleData.cover.dateRange}</p>
              <div className="my-5 h-px w-24 bg-navy-border" />
              <p className="text-[14px] font-medium text-ink">{visibleData.cover.healthBadge}</p>
              {visibleData.cover.budgetSummary && <p className="mt-2 text-[13px] text-ink-muted">{visibleData.cover.budgetSummary}</p>}
            </div>
          </div>
          {visibleData.isPaused && visibleData.pausedMessage && (
            <p className="mx-auto mt-4 max-w-2xl rounded-md border border-navy-border bg-navy-panel px-4 py-3 text-center text-[13px] text-ink-muted">
              {visibleData.pausedMessage}
            </p>
          )}
        </section>

        {visibleData.campaigns.map((c) => (
          <section key={`campaign-${c.campaignName}`} className={slideClass}>
            <CampaignCard campaign={c} reportType={reportTypeLabel(visibleData)} />
          </section>
        ))}

        {adSets.map((a, i) => (
          <section key={`adset-${a.campaignName}-${a.adSetName}-${i}`} className={slideClass}>
            <AdSetCard adSet={a} platform={visibleData.platform} reportType={reportTypeLabel(visibleData)} />
          </section>
        ))}

        {showOverview && chart && chart.donutSegments && (
          <section className={slideClass}>
            <MtdOverviewSlide chart={chart} />
          </section>
        )}

        {showCombinedTotal && (
        <section className={slideClass}>
          <SlideCard>
            <h2 className="mb-4 text-[22px] font-bold text-ink">Monthly Campaign Performance Overview</h2>
            <CombinedTotalTable data={visibleData} />
          </SlideCard>
        </section>
        )}

        {showMetricGuide && (
        <section className={slideClass}>
          <MetricGuideSection metricGuide={metricGuide} />
        </section>
        )}
      </main>

      {!isPrint && (
      <footer style={{ textAlign: "center", padding: "32px 24px", borderTop: "1px solid #1e3a5f", marginTop: "40px" }}>
        <div style={{ color: "#94a3b8", fontSize: "12px" }}>This report was generated using NextReport · nextreport.in</div>
        <div style={{ color: "#64748b", fontSize: "11px", marginTop: "4px" }}>Generated on {generatedDate}</div>
      </footer>
      )}
    </div>
  );
}
