import Link from "next/link";
import type { Metadata } from "next";
import { auth } from "@/lib/auth";
import { PublicNav } from "@/components/public-nav";
import { BetaBanner } from "@/components/beta-banner";

export const metadata: Metadata = {
  title: "Terms of Service — NextReport",
};

export default async function TermsPage() {
  const session = await auth();
  const loggedIn = !!session?.user;

  return (
    <>
      <BetaBanner />
      <PublicNav loggedIn={loggedIn} />
      <main className="mx-auto w-full max-w-2xl flex-1 px-6 py-16">
      <Link href="/" className="text-sm text-accent hover:underline">
        ← Back to NextReport
      </Link>

      <h1 className="mt-6 text-3xl font-semibold text-white">Terms of Service</h1>
      <p className="mt-2 text-sm text-ink-muted">Effective date: July 24, 2026</p>

      <div className="mt-8 space-y-8 text-sm leading-relaxed text-ink-secondary">
        <p>
          These Terms of Service (&ldquo;Terms&rdquo;) govern your use of NextReport,
          the web application available at{" "}
          <span className="text-white">nextreport.in</span> (the
          &ldquo;Service&rdquo;), operated by NextReport (&ldquo;we,&rdquo;
          &ldquo;us,&rdquo; or &ldquo;our&rdquo;). By creating an account or using the
          Service, you agree to these Terms.
        </p>

        <section>
          <h2 className="mb-2 text-lg font-medium text-white">1. The Service</h2>
          <p>
            NextReport lets you upload Meta Ads (and similar) performance exports and
            generates branded PowerPoint reports from that data, optionally including
            AI-written insights using API keys you provide.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-medium text-white">2. Your account</h2>
          <p>
            You&apos;re responsible for maintaining the confidentiality of your login
            credentials and for all activity under your account. Notify us immediately
            at{" "}
            <a href="mailto:hello@nextreport.in" className="text-accent hover:underline">
              hello@nextreport.in
            </a>{" "}
            if you suspect unauthorised use.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-medium text-white">3. Your content</h2>
          <p>
            You retain all rights to the data you upload and the reports NextReport
            generates for you. You&apos;re responsible for having the necessary rights
            and permissions to upload and process that data, and for the accuracy of
            any third-party API keys you provide.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-medium text-white">4. Acceptable use</h2>
          <p>You agree not to:</p>
          <ul className="mt-2 list-inside list-disc space-y-1.5">
            <li>use the Service for any unlawful purpose;</li>
            <li>attempt to gain unauthorised access to other accounts or our systems;</li>
            <li>upload malicious files or content that infringes on others&apos; rights; or</li>
            <li>interfere with or disrupt the integrity or performance of the Service.</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-medium text-white">5. AI-generated content</h2>
          <p>
            Where you enable AI-written insights, that content is generated by
            third-party AI providers (such as Anthropic or Google Gemini) using API keys
            you supply. We do not guarantee the accuracy of AI-generated text, and you
            should review report content before sharing it with clients.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-medium text-white">6. Third-party services</h2>
          <p>
            The Service relies on third-party infrastructure providers, including
            Vercel, Supabase, Google, Anthropic, and Google Gemini. Your use of the Service
            is also subject to those providers&apos; own terms where applicable.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-medium text-white">7. Disclaimer and limitation of liability</h2>
          <p>
            The Service is provided &ldquo;as is&rdquo; without warranties of any
            kind. To the fullest extent permitted by law, NextReport is not liable for
            any indirect, incidental, or consequential damages arising from your use
            of the Service.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-medium text-white">8. Termination</h2>
          <p>
            You may stop using the Service and delete your account at any time. We may
            suspend or terminate accounts that violate these Terms.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-medium text-white">9. Changes to these Terms</h2>
          <p>
            We may update these Terms from time to time. Continued use of the Service
            after changes take effect constitutes acceptance of the updated Terms.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-medium text-white">10. Governing law</h2>
          <p>These Terms are governed by the laws of India.</p>
        </section>

        <section>
          <h2 className="mb-2 text-lg font-medium text-white">11. Contact us</h2>
          <p>
            Questions about these Terms? Email us at{" "}
            <a href="mailto:hello@nextreport.in" className="text-accent hover:underline">
              hello@nextreport.in
            </a>
            .
          </p>
        </section>
      </div>
      </main>
    </>
  );
}
